apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-0548c8af033fa2f30
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-018cd8c2a0964ea19
      my-new-stack-PublicSubnet02:
        id: subnet-0b7c9c95704352294	
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-00d1a3993aa2d6026
      my-new-stack-PrivateSubnet02:
        id: subnet-08a71d36a3c8ddfe3

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true