# Generated by Django 4.1.1 on 2022-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_apartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/villas')),
                ('price', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('bed', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='apartments',
            name='image',
            field=models.FileField(upload_to='images/apartments'),
        ),
    ]
