# Generated by Django 4.1.1 on 2022-10-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_garage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.apartments')),
                ('B', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.building')),
                ('G', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.garage')),
                ('H', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.house')),
                ('O', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.office')),
                ('S', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.shop')),
                ('T', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.townhouse')),
                ('V', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.villas')),
            ],
        ),
    ]
