# Generated by Django 4.1.1 on 2022-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_commonproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='name',
            field=models.CharField(default='Apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default='Building', max_length=50),
        ),
        migrations.AddField(
            model_name='garage',
            name='name',
            field=models.CharField(default='Garage', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(default='Office', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='Shop', max_length=50),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='name',
            field=models.CharField(default='Townhouse', max_length=50),
        ),
        migrations.AddField(
            model_name='villas',
            name='name',
            field=models.CharField(default='Villa', max_length=50),
        ),
    ]
