# Generated by Django 4.1.1 on 2022-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_apartments_name_building_name_garage_name_house_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='garage',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
        migrations.AddField(
            model_name='villas',
            name='city',
            field=models.CharField(default='Jaipur', max_length=50),
        ),
    ]
