# Generated by Django 4.1.1 on 2022-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_apartments_price_alter_building_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='garage',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='office',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='villas',
            name='price',
            field=models.IntegerField(default=6),
        ),
    ]
