# Generated by Django 4.1.1 on 2022-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='Bhk',
            field=models.CharField(default='2 BHK', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='additionalroom',
            field=models.CharField(default='Room', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='approved',
            field=models.CharField(default='Yes', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cornerprop',
            field=models.CharField(default='NO', max_length=5),
        ),
        migrations.AddField(
            model_name='apartments',
            name='floors',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='apartments',
            name='image1',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/ApartmentDetail'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='image2',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/ApartmentDetail'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='image3',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/ApartmentDetail'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='landmark',
            field=models.CharField(default='Near Tonk Road', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='rate',
            field=models.CharField(default='₹ 54216/-', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='status',
            field=models.CharField(default='Fresh', max_length=50),
        ),
        migrations.AddField(
            model_name='apartments',
            name='tokenamount',
            field=models.CharField(default='500000', max_length=50),
        ),
    ]
