# Generated by Django 4.1.1 on 2022-10-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_alter_apartments_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='aprtdetail',
            field=models.CharField(default='apartmentdetail', max_length=50),
        ),
    ]
