# Generated by Django 4.1.1 on 2022-10-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_apartments_image_alter_apartments_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='aprtdetail',
            new_name='detail',
        ),
    ]
