# Generated by Django 4.1.1 on 2022-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_rename_aprtdetail_apartments_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='detail',
            field=models.CharField(default='buildingdetail', max_length=50),
        ),
        migrations.AddField(
            model_name='garage',
            name='detail',
            field=models.CharField(default='garagedetail', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='detail',
            field=models.CharField(default='housedetail', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='detail',
            field=models.CharField(default='officedetail', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='detail',
            field=models.CharField(default='shopdetail', max_length=50),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='detail',
            field=models.CharField(default='townhousedetail', max_length=50),
        ),
        migrations.AddField(
            model_name='villas',
            name='detail',
            field=models.CharField(default='villadetail', max_length=50),
        ),
    ]
