# Generated by Django 4.1.1 on 2022-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_villas_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='approved',
            field=models.CharField(default='Yes', max_length=50),
        ),
    ]
