# Generated by Django 4.1.1 on 2022-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_villas_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villas',
            name='bed',
            field=models.IntegerField(default=5),
        ),
    ]
