# Generated by Django 4.1.1 on 2022-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_villas_bath'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='landmark',
            field=models.CharField(default='Near Tonk Road', max_length=50),
        ),
    ]
