# Generated by Django 4.1.1 on 2022-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_villas_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villas',
            name='area',
            field=models.CharField(default=2245, max_length=50),
        ),
    ]
