# Generated by Django 4.1.1 on 2022-10-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_alter_villas_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villas',
            name='area',
            field=models.CharField(default='2245', max_length=50),
        ),
    ]
