# Generated by Django 4.1.1 on 2022-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_alter_villas_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='rate',
            field=models.CharField(default='54216', max_length=50),
        ),
    ]
