# Generated by Django 4.1.1 on 2022-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_villas_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='tokenamount',
            field=models.CharField(default='500000', max_length=50),
        ),
    ]
