# Generated by Django 4.1.1 on 2022-10-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_villas_tokenamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='additionalroom',
            field=models.CharField(default='Fram House', max_length=50),
        ),
    ]
