# Generated by Django 4.1.1 on 2022-10-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_villas_image1_villas_image2_villas_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/villas'),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/villas'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/villas'),
        ),
    ]
