# Generated by Django 4.1.1 on 2022-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0038_house_additionalroom_house_cornerprop_house_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Bhk',
            field=models.IntegerField(default=2),
        ),
    ]
