# Generated by Django 4.1.1 on 2022-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_house_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image1',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/Office'),
        ),
        migrations.AddField(
            model_name='office',
            name='image2',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/Office'),
        ),
        migrations.AddField(
            model_name='office',
            name='image3',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/Office'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/House'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/House'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.FileField(default='images/v8.jpg', max_length=200, upload_to='images/House'),
        ),
    ]
