# Generated by Django 4.1.1 on 2022-10-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0041_office_image1_office_image2_office_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='approved',
            field=models.CharField(default='Yes', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='Bhk',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='office',
            name='approved',
            field=models.CharField(default='Yes', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='bath',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='office',
            name='landmark',
            field=models.CharField(default='Near Tonk Road', max_length=50),
        ),
    ]
