# Generated by Django 4.1.1 on 2022-10-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_house_approved_office_bhk_office_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='rate',
            field=models.CharField(default='54216', max_length=50),
        ),
    ]
