# Generated by Django 4.1.1 on 2022-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0043_office_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='additionalroom',
            field=models.CharField(default='Room', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='tokenamount',
            field=models.CharField(default='500000', max_length=50),
        ),
    ]
