# Generated by Django 4.1.1 on 2022-10-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0048_building_typeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='bath',
        ),
    ]
