# Generated by Django 4.1.1 on 2022-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0052_garage_bhk_garage_additionalroom_garage_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/Agents')),
                ('fburl', models.CharField(max_length=50)),
                ('twiturl', models.CharField(max_length=50)),
                ('instaurl', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
