# Generated by Django 4.1.1 on 2022-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0055_apartments_altcontact_apartments_contactdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='title',
            field=models.CharField(default='Apartment', max_length=50),
        ),
    ]
