# Generated by Django 4.1.1 on 2022-10-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0058_addproperty_remove_apartments_altcontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='floors',
        ),
    ]
