# Generated by Django 4.1.1 on 2022-10-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0060_clientreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyagents',
            name='deals',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='propertyagents',
            name='exp',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AddField(
            model_name='propertyagents',
            name='firm',
            field=models.CharField(default='Aashiyana Property', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyagents',
            name='address',
            field=models.CharField(default='Pratap Nagar Sector 16', max_length=50),
        ),
    ]
