# Generated by Django 4.1.1 on 2022-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0061_propertyagents_deals_propertyagents_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyagents',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
